trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        displayName: "Build frontend web application"
        steps:
          - task: UseNode@1
            inputs:
              version: "18.17"
            displayName: "Install Node.js"

          - script: npm install
            displayName: "Install dependencies"

          - script: rm -rf out
            displayName: "Remove cached builds"

          - script: npm run build
            displayName: "Build application"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "out"
              artifactName: "fe-art"

  # - stage: Deploy
  #   jobs:
  #     - job: DeployJob
  #       displayName: 'Deploy to Azure App Service'
  #       steps:
  #         - task: DownloadBuildArtifacts@0
  #           inputs:
  #             artifactName: 'webapp'
  #             downloadPath: '$(System.ArtifactsDirectory)/webapp'

  #         - task: AzureRmWebAppDeployment@4
  #           inputs:
  #             ConnectionType: 'AzureRM'
  #             azureSubscription: 'AzureSubscription'
  #             appType: 'webAppLinux'
  #             WebAppName: 'mywebapp'
  #             packageForLinux: '$(System.ArtifactsDirectory)/webapp/**/*.zip'
