trigger:
  tags:
    include:
      - "*"

pool:
  vmImage: "ubuntu-latest"

stages:
  - template: "azure-pipelines-template-build-stage.yaml"

# stages:
#   - stage: Build
#     jobs:
#       - job: BuildJob
#         displayName: "Build frontend web application"
#         steps:
#           - task: UseNode@1
#             displayName: "Install Node.js"
#             inputs:
#               version: "18.17"

#           - script: npm install
#             displayName: "Install dependencies"

#           - script: rm -rf out
#             displayName: "Remove cached builds"

#           - script: npm run build
#             displayName: "Build application"

#           - task: ArchiveFiles@2
#             displayName: "Create archive"
#             inputs:
#               rootFolderOrFile: $(Build.Repository.LocalPath)/out
#               includeRootFolder: false
#               archiveType: zip
#               archiveFile: $(Build.SourceBranchName).zip
#               replaceExistingArchive: false
#               verbose: true

#           - task: PublishPipelineArtifact@1
#             displayName: "Publish artifact locally"
#             inputs:
#               targetPath: $(Build.SourceBranchName).zip
#               artifactName: $(Build.SourceBranchName).zip

  # - stage:
  #   jobs:
  #     - job: PublishArtifactJob
  #       displayName: "Publish artifact to Blob"
  #       steps:
  #         - task: AzureFileCopy@4
  #           inputs:
  #             SourcePath: $(Build.SourceBranchName).zip
  #             azureSubscription: "Free Trial"
  #             Destination: "AzureBlob"
  #             storage: "stgazdevopstest"
  #             ContainerName: "fe-art-artifacts"
  # - stage: Deploy
  #   jobs:
  #     - job: DeployJob
  #       displayName: 'Deploy to Azure App Service'
  #       steps:
  #         - task: DownloadBuildArtifacts@0
  #           inputs:
  #             artifactName: 'webapp'
  #             downloadPath: '$(System.ArtifactsDirectory)/webapp'

  #         - task: AzureRmWebAppDeployment@4
  #           inputs:
  #             ConnectionType: 'AzureRM'
  #             azureSubscription: 'AzureSubscription'
  #             appType: 'webAppLinux'
  #             WebAppName: 'mywebapp'
  #             packageForLinux: '$(System.ArtifactsDirectory)/webapp/**/*.zip'
