parameters:
- name: tagNumber
  displayName: 'Tag Number'
  type: string
  default: '1.0.0'
- name: message
  displayName: 'Message to be added when creating the tag'
  type: string
  default: 'Created release tag'

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true
  - script: |
      git tag -a ${{ parameters.tagNumber }} -m ${{ parameters.message }}
      git push origin tag ${{ parameters.tagNumber }}
